apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyrewheel-worker
spec:
  template:
    spec:
      containers:
        - name: worker
          env:
            - name: QE_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: flyrewheel-s3
                  key: AWS_ACCESS_KEY_ID
            - name: QE_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: flyrewheel-s3
                  key: AWS_SECRET_ACCESS_KEY
